# Build and Release Workflow
# Phase 3: Build Artifacts for Production
# Triggers on release tags

name: Build Release Artifacts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g., v1.0.0)'
        required: true

jobs:
  build:
    name: Build Production Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install Dependencies (Production)
        run: composer install --no-dev --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan event:cache

      - name: Create Release Archive
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          tar -czf fahras-api-${VERSION}.tar.gz \
            --exclude='.git' \
            --exclude='.forgejo' \
            --exclude='tests' \
            --exclude='node_modules' \
            --exclude='storage/logs/*' \
            --exclude='storage/framework/cache/*' \
            --exclude='storage/framework/sessions/*' \
            --exclude='storage/framework/views/*' \
            .

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fahras-api-release
          path: fahras-api-*.tar.gz
          retention-days: 90

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.CONTAINER_REGISTRY_URL }}/fahras/api
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ secrets.CONTAINER_REGISTRY_URL }}/fahras/api:buildcache
          cache-to: type=registry,ref=${{ secrets.CONTAINER_REGISTRY_URL }}/fahras/api:buildcache,mode=max

