# Laravel Backend CI/CD Pipeline for Forgejo Actions
# Phase 3: Automated Testing & Quality Assurance
# Based on Gemini recommendations for Laravel CI/CD best practices

name: Laravel Backend CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  # Main test job that runs all our tests
  test:
    name: PHP ${{ matrix.php-version }} on ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2']
        os: [ubuntu-latest]
    
    # Service containers to run with the job
    services:
      # PostgreSQL database for testing
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: laravel_test
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      # Redis for cache and sessions
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      # 1. Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set up PHP environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo, pdo_pgsql, pdo_mysql, bcmath, gd, mbstring, zip, redis, opcache
          tools: composer:v2
          coverage: none

      # 3. Cache Composer dependencies
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      # 4. Install Composer dependencies
      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction --no-suggest

      # 5. Prepare Laravel Environment
      - name: Prepare Environment
        run: |
          # Create the .env file from the example
          cp .env.example .env
          
          # Generate the application key
          php artisan key:generate
          
          # Set CI-specific environment variables
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=postgres" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=laravel_test" >> .env
          echo "DB_USERNAME=test_user" >> .env
          echo "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "APP_ENV=testing" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "CACHE_DRIVER=redis" >> .env
          echo "SESSION_DRIVER=redis" >> .env
          echo "QUEUE_CONNECTION=redis" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "FILESYSTEM_DISK=local" >> .env
          echo "LOG_CHANNEL=stderr" >> .env

      # 6. Set up storage permissions
      - name: Setup Storage
        run: |
          mkdir -p storage/framework/{sessions,views,cache}
          mkdir -p storage/logs
          chmod -R 775 storage bootstrap/cache

      # 7. Run Database Migrations
      - name: Run Migrations
        run: php artisan migrate --force

      # 8. Run Database Seeders (if needed for tests)
      - name: Seed Database
        run: php artisan db:seed --force
        continue-on-error: true

      # 9. Clear and cache configuration
      - name: Optimize Application
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear

      # 10. Run Tests
      - name: Execute tests (PHPUnit)
        run: php artisan test --parallel

      # 11. Generate Code Coverage (optional)
      - name: Generate Coverage Report
        run: php artisan test --coverage --min=80
        continue-on-error: true

  # Code Quality Checks
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # Laravel Pint for code formatting
      - name: Run Laravel Pint
        run: vendor/bin/pint --test
        continue-on-error: true

  # Security Audit
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      # Composer security audit
      - name: Run Composer Audit
        run: composer audit --format=json > composer-audit.json || true
        continue-on-error: true

      - name: Upload Audit Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: composer-audit-report
          path: composer-audit.json
          retention-days: 30

